export default {
  EMAIL_ALREADY_EXISTS: "Email already exists!",
  EMAIL_IS_REQUIRED: "Email is required!",
  INVALID_EMAIL: "Invalid email",
  SERVER_ERROR: "Server error",
  USER_CREATED: "User created successfully",
  LOGIN_SUCCESS: "Login successful",
  PASSWORD_LENGTH: 8,
  PASSWORD_TOO_SHORT: "Password must be 8 characters or more",
  PASSWORD_IS_REQUIRED: "Password is required",
  INVALID_LOGIN: "Invalid login",
  WELCOME_USER: (name: string) => `Welcome ${name}`,
  EMAIL_WAS_NOT_SENT: "Email was not sent",
  USER_DOES_NOT_EXIST: "User does not exist",
  RESET_PASSWORD_EMAIL_SENT: "Reset password email was sent successfully",
  TOKEN_IS_REQUIRED: "Token is required!",
  PASSWORD_RESET_SUCCESSFULLY: "Password reset successfully!",
  TOKEN_EXPIRED: "Token has expired",
};
